.TH "gpxviewer" "1"
.SH "NAME"
gpxviewer \- GTK application to look at GPS traces collected in the GPX format
.SH "SYNOPSIS"
\fB
.SH "DESCRIPTION"
.B gpxviewer
 allows the user to load a GPS trace, in the GPX file format, and read it in 
 a presentable way. You are shown a few statistics, such as the duration or 
 maximum speed. You are also shown the trace on an openstreetmap map, where 
 you can scroll around and zoom.
.SH "BUGS"
You can report bugs you find in this software at 
http://bugs.launchpad.net/gpxviewer
.SH "AUTHOR"
.PP
This manual page was written by Andrew Gee <andrew@andrewgee.org> 
for the \fBDebian GNU/Linux\fP system.
